application_port: 8000

database:
  host: "ep-icy-unit-ahcd70ji-pooler.c-3.us-east-1.aws.neon.tech"
  port: 5432
  database_name: "wizard-backend"
  require_ssl: true

email_client:
  base_url: "localhost"
  sender_email: "test@gmail.com"
  auth_token: "test_token"
  timeout_milliseconds: 10000
