application_port: 8000

database:
  host: "0.0.0.0"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "wizard_blog_backend"

email_client:
  base_url: "localhost"
  sender_email: "test@gmail.com"
  auth_token: "test_token"
  timeout_milliseconds: 10000
